### ISSUE TITLE
changing weapons crashes the game

### ISSUE THREAD

**Issue by Dustlol** [M-FeD/Fedoraware#103]
not aways but it happens a lot, its pretty annoying when u crash tf2 10 times to inject just to have it close in the middle of a match bc u changed weapons

**Comment by km-ch** [comment]
Can confirm, a friend of mine who was using Fedoraware yesterday had the same issue.

**Comment by Dustlol** [comment]
> didnt happen to me

just happened to me again :D

**Comment by M-FeD** [comment]
ok well i cant get it to happen

**Comment by M-FeD** [comment]
still cant get this to happen
