### ISSUE TITLE
compilation problem

### ISSUE THREAD

**Issue by HeXz69** [M-FeD/Fedoraware#116]
Maybe I'm retarded, but all of a sudden I'm getting these errors where I didn't have any problems before
translation of one of them from my super language: C2641 Cannot infer arguments for user "CVar" (TeamFortress2 \ Utils \ Events \ Events.cpp source file compilation) TeamFortress2 D: *** \ *** \ *** \\ Fedoraware-main \ Property SE \ TeamFortress2 \ TeamFortress2 \ Functions \ Vars.h 56
screenshot:
![devenv_CxUquAKCzk](https://user-images.githubusercontent.com/61068958/139542519-653aef28-7578-4016-816b-615805a52033.png)
edit: each error comes from the Vars.h file

**Comment by JAGNEmk** [comment]
Maybe use x86 | Release for compiling hm?

**Comment by HeXz69** [comment]
I use x86

**Comment by HeXz69** [comment]
I have no problem with other sources, this one is only in Fedoraware and pure SEOwned and yesterday it compiled normally

**Comment by SinnerTF2** [comment]
make sure you are using c++17

![gif](https://krypt0n.eu/sharex/jN3l9G3Ktj.gif)

**Comment by HeXz69** [comment]
I'm using because I haven't changed anything in the project properties

**Comment by M-FeD** [comment]
dont care

**Comment by SinnerTF2** [comment]
l0l!
