### ISSUE TITLE
I cannot download it pls help!!! 

### ISSUE THREAD

**Issue by Mish888** [M-FeD/Fedoraware#123]
**Fedoraware Version Date:**  

## Steps to reproduce:  
- [ ] I am able to consistently reproduce this error

1. Enable X
2. Do Y
3. Notice Z

## Screenshot of cheats enabled  

- [ ] I have included the steps to reproduce to the best I am able to share.

**Comment by M-FeD** [comment]
shut the fuck up???

**Comment by xAl0n3** [comment]
a
