### ISSUE TITLE
DT Bug (or not)

### ISSUE THREAD

**Issue by thirdy1215** [M-FeD/Fedoraware#125]
When using any hitscan weapon with DT and shooting it on players you suddenly stop moving and have to press wsad again. 

(Im predicting that your gonna say "I dont care " :). )

**Comment by M-FeD** [comment]
ok

**Comment by M-FeD** [comment]
i fucked up the

**Comment by Robert29541** [comment]
im having the same problem

**Comment by M-FeD** [comment]
fuck you robert

**Comment by Robert29541** [comment]
u can m-FeD my dog if u want to

**Comment by M-FeD** [comment]
sorry

**Comment by thirdy1215** [comment]
Closing It Bc of this -> https://www.youtube.com/watch?v=YfFNAqXO_4I
