### ISSUE TITLE
Improvements to crithack

### ISSUE THREAD

**Issue by rikodeine** [M-FeD/Fedoraware#126]
could make it way better by just checking for critbans

**Comment by macedoniaN1337** [comment]
no

**Comment by M-FeD** [comment]
yoo that would be sick how do i do that

**Comment by rikodeine** [comment]
& avoid random crits

**Comment by M-FeD** [comment]
> 
> 
> & avoid random crits

that would be cool too, how do i do that

**Comment by rikodeine** [comment]
https://github.com/nullworks/cathook/blob/master/src/crits.cpp

**Comment by rikodeine** [comment]
@M-FeD

**Comment by rikodeine** [comment]
has all the good shit u need like avoid random crits, checking for crit bans

**Comment by raspimana** [comment]
> 
> 
> has all the good shit u need like avoid random crits, checking for crit bans

crit bans? yassssssssssssss

**Comment by hyperventilation** [comment]
how are you so smart....

**Comment by M-FeD** [comment]
bitches all on my dick and on my balls
