### ISSUE TITLE
Game crashing when injecting FWare(Release).dll

### ISSUE THREAD

**Issue by InfamousGalaxy** [M-FeD/Fedoraware#127]
**Fedoraware Version Date:**
MSBuild#66 
https://github.com/M-FeD/Fedoraware/actions/runs/1425773026

## Config used:

A normal default config, didn't change a thing. Couldn't even open the menu to make a config lol.

## Description:  

Game crashes when cheat gets launched, that's it, can't even have a chance to open the menu

## Steps to reproduce:  
- [✅] I am able to consistently reproduce this error

Anytime the FedoraWare is injected the game crashes, can't get any further.

Simply launch it and join a 2fort match (could be on other maps too but haven't tested it yet)
Ran fine on a different map though. (example jumpacademy mga server)

## Additional context 

Don't know really, horrible at codes or understanding them in that case
Used the injector mention in the guide, by Xenos latest release.
Crash also happens when using TFGhost.

## Screenshot of cheats enabled  

Video is better, it's unlisted.
Game crashing using Xenos: https://youtu.be/vx8kdj-V-Mw
Game crashing using TFGhost: https://youtu.be/EvptR7pOsiE (couldn't even switch back to game lol)
- [✅] I have included the steps to reproduce to the best I am able to share

**Comment by m0nnk3y** [comment]
this is happening with me aswell

**Comment by Heil-tf2** [comment]
same

**Comment by imdecending** [comment]
same if i inject try and join a game it crashes,but if i joinbefore injecting it will crash after 5-10 minutes

**Comment by InfamousGalaxy** [comment]
Would like to update this and say, haven''t experienced any crashing using the msbuild#70. 
(https://github.com/M-FeD/Fedoraware/actions/runs/1432378274)

Don't really know what the issue was but this issue can be closed
