### ISSUE TITLE
Auto Airblast Bug

### ISSUE THREAD

**Issue by thirdy1215** [M-FeD/Fedoraware#128]
When **Only** Enabling  Silent In Auto Airblast doesn't work. But somehow works fine when Rage is enabled with silent
(Question) The Fuck does full Update do??
(Suggestion) Also, Can you make a Target button or a Button the specifically targets the player first then the other people for the player list Because I don't want to go through ignoring more than 12 people and getting killed because I forgot to unlist every poeple

And Finally...
![image](https://user-images.githubusercontent.com/75602290/140637258-f73df994-bf3d-4d61-a42c-6fcf40038b71.png)

**Comment by M-FeD** [comment]
not a bug kiill yourself

**Comment by thirdy1215** [comment]
> not a bug kiill yourself

My dumbass forgot to get the newer dll and is now working. Sorry
