### ISSUE TITLE
Auto Backstab sometimes just stops

### ISSUE THREAD

**Issue by Habnone** [M-FeD/Fedoraware#130]
Imma not use that template bc its just in the tittle I use CFG2.seo

**Comment by M-FeD** [comment]
ok

**Comment by M-FeD** [comment]
sometimes i just stop

**Comment by M-FeD** [comment]
do u like figs

**Comment by raspimana** [comment]
> do u like figs
personally i never tried them, but they look nice.
i'll try them the next time i go to the store
