### ISSUE TITLE
bullet tracers !JJ!J!#J!@KJ#

### ISSUE THREAD

**Issue by hospitalisation** [M-FeD/Fedoraware#131]
https://www.unknowncheats.me/forum/team-fortress-2-a/476726-bullet-tracers.html

ok this.

**Comment by hyperventilation** [comment]
too hard to implement, sorry

**Comment by IamIndeedGamingAsHardAsICan03489** [comment]
> too hard to implement, sorry

braindead ape

**Comment by M-FeD** [comment]
dont caaaaaaaaaaaaaaaaaaaaaaaareeeeeeeeeeeeeeeeeeeeee you WILL use the debug overlay tracers and you WILL like them
