### ISSUE TITLE
Auto Backstab stops working after starting a new game

### ISSUE THREAD

**Issue by Habnone** [M-FeD/Fedoraware#132]
**Fedoraware Version Date:**  
Latest

## Config used:
https://www.mediafire.com/file/o6ry0iitp61hz63/CFG2.seo/file

## Description:  
When you turn on auto backstab first time it works fine, but then after a new match starts, it just does not trigger anymore even when im standing behind the enemy.

## Steps to reproduce:  
1. Enable auto backstab
2. Join a game (I played DeGroot Keep)
3. Play some time as spy
4. After some time or after a new game starts it just stops working
5. Only works after you restart tf2

## Screenshot of cheats enabled  
![Brain Damage](https://user-images.githubusercontent.com/92119355/140808819-b131b9dd-48fd-4254-b07e-5578e3cb8128.png)

**Comment by M-FeD** [comment]
i really do not care sorry D:

**Comment by Habnone** [comment]
> i really do not care sorry D:

Then wtf should I do? Im too dum to code and its the best cheat ever and I love you

**Comment by M-FeD** [comment]
make it work

**Comment by AscendedSion** [comment]
purely a skill issue.
Autobackstab never breaks down for me.

**Comment by M-FeD** [comment]
you are full of faeces and pee and stuff that isnt good so i think u should shut up :)
