### ISSUE TITLE
Broken Stuff and Bugs

### ISSUE THREAD

**Issue by XenoxUSser** [M-FeD/Fedoraware#133]
1. catreply no longer functions bots target you
2. chams still break and turn black or invis so pls readd the fix chams button since waiting for self fix can take from minutes to hours
3. scouts dt is 20 ticks rather than 24
4. mvm medics shield and revive things make aimbot stop targeting enemies behind them

**Comment by SinnerTF2** [comment]
> 1. catreply no longer functions bots target you
yeah because most bots dont use cathooks identify method

**Comment by XenoxUSser** [comment]
> > 1. catreply no longer functions bots target you
> 
> yeah because most bots dont use cathooks identify method

then how come cathook users are immune to them? did i miss something

**Comment by M-FeD** [comment]
fartfartcfatrfartfartfartcfatrfartfartfartcfatrfartfartfartcfatrfart

**Comment by M-FeD** [comment]
bla bla bla i do not car

**Comment by M-FeD** [comment]
yooo that rhymed thats so swag and cool

**Comment by M-FeD** [comment]
oops i reopened i didnt mean to sorryyyyyy
