### ISSUE TITLE
backtrack/fake letancy

### ISSUE THREAD

**Issue by dripuser** [M-FeD/Fedoraware#134]
pls add backtrack / fake letancy it would be cool with spy autobackstab you know 
also backtrack chams/esp with it

**Comment by xAl0n3** [comment]
shut up

> pls add backtrack / fake letancy it would be cool with spy autobackstab you know also backtrack chams/esp with it

SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP SHUT UP
