### ISSUE TITLE
The heavy crithack doesnt work

### ISSUE THREAD

**Issue by ComBap** [M-FeD/Fedoraware#147]
It just crits when it wants to (even with crit bucket full XDDDDDD), this also goes for pistols and stuff.

**Comment by SinnerK0N** [comment]
even when the crit bucket is full?? OMFG XDDDDDDDD LMFAOOOO

**Comment by M-FeD** [comment]
really..........

**Comment by M-FeD** [comment]
im so sorry i will make it crit when the bucket is full next tiem

**Comment by ComBap** [comment]
Wait im just retarded
