### ISSUE TITLE
issues while building

### ISSUE THREAD

**Issue by canedoly** [M-FeD/Fedoraware#15]
so i've tried building the latest version
this is Release x86
![image](https://user-images.githubusercontent.com/81353241/132551724-3a81fdb9-c2d0-4342-ac60-0b22df058426.png)

**Comment by M-FeD** [comment]
yea maiN had this issue too, not sure why cos it works fine for me, maybe its missing an include?

**Comment by M-FeD** [comment]
for the mean time you could probably just comment all code related to saving/loading std::strings out

**Comment by M-FeD** [comment]
https://github.com/M-FeD/Fedoraware/commit/9eb4fdeeff99c3c2ea0dcf342f2317ff9a513aef

Reverted this, since it just seems to mess stuff up than actualy fix anything, strings still wont load now though
