### ISSUE TITLE
Crithack stuck on "Crit banned"

### ISSUE THREAD

**Issue by macedoniaN1337** [M-FeD/Fedoraware#160]
![image](https://user-images.githubusercontent.com/91955595/149155580-c305fc43-12e5-42a5-9380-de45ccbc9313.png)

Title says it all

**Comment by canedoly** [comment]
idk, i still could crit even tho i'm "crit banned" did you hold your critkey and tried shooting?

**Comment by macedoniaN1337** [comment]
> idk, i still could crit even tho i'm "crit banned" did you hold your critkey and tried shooting?

this happened a few times only, but i'm assuming it was only random crits tbh, and yeah i did try shooting with it with the critkey, obviously.

**Comment by M-FeD** [comment]
Honestly the crit banned thing isn't accurate, I just noticed that the numbers being different and assumed it was because I was crit banned so I made it say that, dunno if you actually are when it says that lol idk how to do crit hack

**Comment by macedoniaN1337** [comment]
> Honestly the crit banned thing isn't accurate, I just noticed that the numbers being different and assumed it was because I was crit banned so I made it say that, dunno if you actually are when it says that lol idk how to do crit hack

looks like pasting cathooks crithack wasnt worth it at the end huh? Xd

**Comment by M-FeD** [comment]
> > Honestly the crit banned thing isn't accurate, I just noticed that the numbers being different and assumed it was because I was crit banned so I made it say that, dunno if you actually are when it says that lol idk how to do crit hack
> 
> looks like pasting cathooks crithack wasnt worth it at the end huh? Xd

it's not cathooks, cathooks crit hack is actually good but every time i've tried pasting that its crashed me l0l

**Comment by macedoniaN1337** [comment]
> it's not cathooks, cathooks crit hack is actually good but every time i've tried pasting that its crashed me l0l

💀 💀 💀 💀 💀 💀
