### ISSUE TITLE
fix bhop for scout :trollface: 

### ISSUE THREAD

**Issue by BeeEllEsss** [M-FeD/Fedoraware#161]
fix bunny hop for scout

**Comment by M-FeD** [comment]
What do you mean fix, it's not broken

**Comment by BeeEllEsss** [comment]
to skip the double jump

**Comment by M-FeD** [comment]
are you retarded

**Comment by M-FeD** [comment]
why would you want to skip the double jump

**Comment by M-FeD** [comment]
i literally can not fathom a single use case in which that would be useful

**Comment by BeeEllEsss** [comment]
yeah im probably retarded anyways thread closed so idrk
