### ISSUE TITLE
movement sim

### ISSUE THREAD

**Issue by canedoly** [M-FeD/Fedoraware#163]
m-fed please add it, 
or should i try to add it somehow, i'm probably gonna fail
also you should make a discord server again

**Comment by zphrus** [comment]
SHUT UPPPPP PLEASE SHUT UP

**Comment by M-FeD** [comment]
i can add it lol just to make sten seethe

**Comment by zphrus** [comment]
NOOOOOOOOOO SSHUT UP GONGLEWARE PREDICTION NO LEAK NOOOOOO

**Comment by M-FeD** [comment]
(hes coping and seething about bullet tracers in 2022 btw)

**Comment by dwordisa3-bytelargebyte** [comment]
go back to your lmao paste pooron

**Comment by M-FeD** [comment]
no

**Comment by zphrus** [comment]
now you're just going too far

**Comment by canedoly** [comment]
do you know what would i need to do, to fix movement simulation?
i've tried adding it but ended up with some unfixed errors I didn't know how to fix

**Comment by zphrus** [comment]
find it out yourself period

**Comment by canedoly** [comment]
thanks for the help dude

**Comment by M-FeD** [comment]
> do you know what would i need to do, to fix movement simulation? i've tried adding it but ended up with some unfixed errors I didn't know how to fix

whats ur problem

**Comment by macedoniaN1337** [comment]
yo zephyr didn't you cope hard a couple months ago? why are you still here retard

**Comment by dwordisa3-bytelargebyte** [comment]
![unknown (3)](https://user-images.githubusercontent.com/31211336/150099417-425530fd-5093-4e5f-b418-235cda356849.png)

**Comment by canedoly** [comment]
nvm i've tried adding it but at the end i just failed, I just can't add it with my level of knowledge in coding, atleast i tried

**Comment by canedoly** [comment]
closed, because it won't be probably added and i can't add it with my knowledge
