### ISSUE TITLE
add more aa settings

### ISSUE THREAD

**Issue by frel0** [M-FeD/Fedoraware#169]
add more aa settings and edge detection if chad

**Comment by HutchyBean** [comment]
ur a  nonce

**Comment by lnx00** [comment]
Added two new AA modes (Spin & Random) in ae1b933b5fa66cb4c8894ba854930c65704c5099

**Comment by M-FeD** [comment]
ur a nonce frel0

**Comment by frel0** [comment]
thank you nigga
