### ISSUE TITLE
add A "Enable Pyrovision" option in visuals

### ISSUE THREAD

**Issue by 123123asd346** [M-FeD/Fedoraware#170]
it would be A neat feature

**Comment by M-FeD** [comment]
why

**Comment by M-FeD** [comment]
ok i added it but it kinda flickers

**Comment by M-FeD** [comment]
[a1995a6a616dd49af6620af5126179f26ba7a802](https://github.com/M-FeD/Fedoraware/commit/a1995a6a616dd49af6620af5126179f26ba7a802)
