### ISSUE TITLE
Handchams Error

### ISSUE THREAD

**Issue by 123123asd346** [M-FeD/Fedoraware#171]
In DMEChams.cpp You Did If "found2" two times thus making glow boost not work.
`				IMaterialVar* pVar = pMaterial->FindVar(_("$phongtint"), &found);
				if (found) {
					pVar->SetVecValue(Color::TOFLOAT(Colors::HandsOverlay.r) * 4, Color::TOFLOAT(Colors::HandsOverlay.g) * 4, Color::TOFLOAT(Colors::HandsOverlay.b) * 4);
				}
				IMaterialVar* pVar2 = pMaterial->FindVar(_("$envmaptint"), &found2);
				if (found2) {
					pVar2->SetVecValue(Color::TOFLOAT(Colors::HandsOverlay.r) * 4, Color::TOFLOAT(Colors::HandsOverlay.g) * 4, Color::TOFLOAT(Colors::HandsOverlay.b) * 4);
				}
				IMaterialVar* pVar3 = pMaterial->FindVar(_("$rimlightboost"), &found3);
				if (found2) {
					pVar3->SetIntValue(Vars::Chams::DME::HandsRimMultiplier.m_Var);
				}`

**Comment by 123123asd346** [comment]
not really A issue but idk how to make A pull request sorry m-fed :)

**Comment by canedoly** [comment]
to make a pull request you gotta make a fork of this cheat and make the changes and come back here and you should be able to pull request

**Comment by M-FeD** [comment]
`				bool found = false;
				bool found2 = false;
				bool found3 = false;
				IMaterialVar* pVar = pMaterial->FindVar(_("$phongtint"), &found);
				if (found) {
					pVar->SetVecValue(Color::TOFLOAT(Colors::HandsOverlay.r) * 4, Color::TOFLOAT(Colors::HandsOverlay.g) * 4, Color::TOFLOAT(Colors::HandsOverlay.b) * 4);
				}
				IMaterialVar* pVar2 = pMaterial->FindVar(_("$envmaptint"), &found2);
				if (found2) {
					pVar2->SetVecValue(Color::TOFLOAT(Colors::HandsOverlay.r) * 4, Color::TOFLOAT(Colors::HandsOverlay.g) * 4, Color::TOFLOAT(Colors::HandsOverlay.b) * 4);
				}
				IMaterialVar* pVar3 = pMaterial->FindVar(_("$rimlightboost"), &found3);
				if (found3) {
					pVar3->SetIntValue(Vars::Chams::DME::HandsRimMultiplier.m_Var);
				}`

I think you have an outdated source or github is acting up because when I just looked into to the DMEChams.cpp file, I only do if (found2) once and do if (found3) correctly...

**Comment by M-FeD** [comment]
Turns out jagne fixed this 4 days ago lol
