### ISSUE TITLE
add bignasty tracer 

### ISSUE THREAD

**Issue by BeeEllEsss** [M-FeD/Fedoraware#172]
bullet_bignasty_impact_chunks
bullet_bignasty_tracer01_blue
bullet_bignasty_tracer01_blue_crit
bullet_bignasty_tracer01_red
bullet_bignasty_tracer01_red_crit

**Comment by M-FeD** [comment]
whats the impact_chunks thing?

**Comment by BeeEllEsss** [comment]
the bullet impact at walls i think

**Comment by 123123asd346** [comment]
thanks for new tracers :trollface:

**Comment by M-FeD** [comment]
i can add the big nasty but not the impact chunks thing cos idk how those work ngl

**Comment by M-FeD** [comment]
interesting development, using these tracers makes the chunks spawn naturally

**Comment by M-FeD** [comment]
https://user-images.githubusercontent.com/31779182/150678739-78cff319-1ab7-47c0-b981-2dba57a678d2.mp4

**Comment by M-FeD** [comment]
pushed
