### ISSUE TITLE
Add noscope lines

### ISSUE THREAD

**Issue by 1230912zdfol** [M-FeD/Fedoraware#176]
I would love it you could ty.

**Comment by M-FeD** [comment]
could you elaborate on what that means? like a line from your gun to where you're aiming when you aren't scoped?

**Comment by M-FeD** [comment]
or like, lines drawn on the screen as a scope crosshair kinda thing, cos there's a convar to enable the crosshair when zoomed `tf_hud_no_crosshair_on_scope_zoom `

**Comment by 1230912zdfol** [comment]
its like the line when you use noscope in nacl

**Comment by M-FeD** [comment]
Screenshot/source? Never used NaCl

**Comment by SinnerK0N** [comment]
![](https://krypt0n.eu/sharex/DTxiV5iwcm.png)
big ugly yes

**Comment by M-FeD** [comment]
yucky, wouldn't use myself but i can add it i guess...

**Comment by 1230912zdfol** [comment]
sorry I just like them.

**Comment by M-FeD** [comment]
I can add them I guess it's like literally 2 lines

**Comment by M-FeD** [comment]
added
