### ISSUE TITLE
aimbot bug

### ISSUE THREAD

**Issue by SomeExtraChips** [M-FeD/Fedoraware#18]
sometimes aimbot just start aiming at feet forever (even changing hitbox group dont fix this)

video showing the issue : https://youtu.be/usCJVsRa1Vw
config i was using : https://i.imgur.com/VL5yPcZ.png

**Comment by JAGNEmk** [comment]
This is a very rare, strange, and annoying bug lmao

**Comment by spook953** [comment]
https://github.com/M-FeD/Fedoraware/blob/main/SE-Owned/TeamFortress2/TeamFortress2/SDK/Main/BaseEntity/BaseEntity.h#L342 is most likely the culprit, should be switched out to return m_vecOrigin() + m_vecViewOffset()

**Comment by M-FeD** [comment]
https://github.com/M-FeD/Fedoraware/commit/760f66601358c64bfd2e52aab98b07c745a6760f
LMK if this is what you meant, @spook953

**Comment by spook953** [comment]
> [760f666](https://github.com/M-FeD/Fedoraware/commit/760f66601358c64bfd2e52aab98b07c745a6760f)
> LMK if this is what you meant, @spook953

ye should be that

**Comment by SomeExtraChips** [comment]
the new update seems to fixed the issue, ive been playing for 2 hours and it didnt happen yet

**Comment by M-FeD** [comment]
> 
> 
> the new update seems to fixed the issue, ive been playing for 2 hours and it didnt happen yet

Will consider this case closed then, thank you spook and thanks for reporting
