### ISSUE TITLE
Anti-AFK not preventing kicks

### ISSUE THREAD

**Issue by km-ch** [M-FeD/Fedoraware#19]
Anti-AFK will jump as expected, but it doesn't stop the game from detecting theat you are AFK
![image](https://user-images.githubusercontent.com/88402387/132928390-61cc0208-7d5d-45b2-b040-d591c5aadeb9.png)

**Comment by M-FeD** [comment]
maybe jumping doesnt stop u getting kicked, didnt know that just sort of guessed tbh

**Comment by M-FeD** [comment]
https://github.com/M-FeD/Fedoraware/commit/f8f45567085327e954773824ea4e3f9ac68c8e6b
