### ISSUE TITLE
Nitro DT indicator style issue & Debugger?

### ISSUE THREAD

**Issue by lnx00** [M-FeD/Fedoraware#199]
Selecting the Nitro indicator for doubletap will fail the assertion and crash the game.
It seems like some ImGui "Pop" method (PopStyleColor?) is called more often than it's corresponding Push method.

Also: How does the debug build work? Injecting it after attaching VS to TF2 will crash the game immediately. I wanted to use the debugger in order to find the cause of this crash but I'm not able to use it

![Image](https://i.imgur.com/iiA5HBS.png)

**Comment by M-FeD** [comment]
uh yeah i was trying to make it like flicker less but it doesnt work lol

**Comment by tf2cheater2013** [comment]
1. build debug
2. attach vs
3. native inject on existing thread

**Comment by lnx00** [comment]
> 1. build debug
> 2. attach vs
> 3. native inject on existing thread

Works now, thanks!

**Comment by M-FeD** [comment]
lol what

**Comment by lnx00** [comment]
The indicator is still not working, but the debugger ist

**Comment by dwordisa3-bytelargebyte** [comment]
![unknown (3)](https://user-images.githubusercontent.com/31211336/151718788-7482e236-5c34-49b2-b951-ba07942fd823.png)

**Comment by lnx00** [comment]
Fixed in #203
