### ISSUE TITLE
Fakelag modes

### ISSUE THREAD

**Issue by 1230912zdfol** [M-FeD/Fedoraware#200]
random, velocity based fakelag like if velocity = 200 change the tick or if it = 400 change the tick.

**Comment by IamIndeedGamingAsHardAsICan03489** [comment]
make it urself LOL

**Comment by 1230912zdfol** [comment]
I have just wanna see it in the repo and im not forking my whole proj

**Comment by IamIndeedGamingAsHardAsICan03489** [comment]
`if (Local->Speed().lenght() >= 200.f)
  bSendPacket = rand() % 12`
  p100 code cope harder

**Comment by 1230912zdfol** [comment]
ok

**Comment by 1230912zdfol** [comment]
don't need to be A dick about it goddamn

**Comment by IamIndeedGamingAsHardAsICan03489** [comment]
> `if (Local->Speed().lenght() >= 200.f) bSendPacket = rand() % 12` p100 code cope harder

actually u better apply more logic to it, cuz thats not gonna work LOL

**Comment by 1230912zdfol** [comment]
nice coding dude

**Comment by 1230912zdfol** [comment]
as ive said ive already made it

**Comment by lnx00** [comment]
It's a good suggestion, no need to close it
