### ISSUE TITLE
discord button invite invalid

### ISSUE THREAD

**Issue by PhoenixAceVFX** [M-FeD/Fedoraware#201]
Not exactly a bug with the cheat but more so with the readme, is the invite link going to be updated or did you only update the serverid for the shield?

**Comment by M-FeD** [comment]
uhh i enabled the widget thing too idk why it doesnt work

**Comment by M-FeD** [comment]
nvm brain moment try it now

**Comment by PhoenixAceVFX** [comment]
yee button works now!
