### ISSUE TITLE
Serious issues guys

### ISSUE THREAD

**Issue by HutchyBean** [M-FeD/Fedoraware#204]
Ok so guys the body part scaler cannot turn off. even worse guys. the slide r goes up in scale of 4 making it impossible to make it 1 AGAIN!!!!!!!

**Comment by HutchyBean** [comment]
also is body scaler supposed to ruin aimbot. is it supposed to be that funny

**Comment by M-FeD** [comment]
Ctrl + click to enter a specific number

**Comment by HutchyBean** [comment]
bonkers

**Comment by JAGNEmk** [comment]
shift + m1 on the slider allows u to input an int with your keyboard iirc

**Comment by M-FeD** [comment]
> also is body scaler supposed to ruin aimbot. is it supposed to be that funny

Could probably fix it but if you're retarded enough to use the body part scaling you deserve it

**Comment by HutchyBean** [comment]
as person who never uses imgui. never knew that

**Comment by JAGNEmk** [comment]
or maybe it was ctrl + m1 idk

**Comment by JAGNEmk** [comment]
while i was typing people alr answered... wow
