### ISSUE TITLE
ARGHHH WHAT ARE THESE BOXES HELP ME

### ISSUE THREAD

**Issue by HutchyBean** [M-FeD/Fedoraware#205]
![image](https://user-images.githubusercontent.com/38333275/151721880-de944560-3246-406a-8b62-a814e344ae4b.png)

**Comment by JAGNEmk** [comment]
fakelag visualizer?

**Comment by M-FeD** [comment]
No

**Comment by M-FeD** [comment]
It's your server side hitboxes (only works locally, baan added it earlier)

**Comment by HutchyBean** [comment]
thats BEAST

**Comment by JAGNEmk** [comment]
Ah.

**Comment by HutchyBean** [comment]
how to turn off. its ugly af

**Comment by M-FeD** [comment]
I have no idea

**Comment by HutchyBean** [comment]
thank you
