### ISSUE TITLE
Simple Pitch Resolver

### ISSUE THREAD

**Issue by SomeExtraChips** [M-FeD/Fedoraware#25]
(not an issue)
few days ago i was messing around with fedoraware source and i dicided to paste the Dumpsterfire resolver on it
its quite simple if you guys want to add it

epic tuto :
1* go to ClientHook.cpp
2* paste this code in FSN >>code https://pastebin.com/raw/qk5p2mFf
3* the code should looks like this : https://i.imgur.com/96kJEcu.png
dont need to change anything in the code cuz i already did some edits to it fits with seowned source, like gInts being g_Interfaces etc...

**Comment by km-ch** [comment]
Why don't you open a PR then? That would be more easy for the developers, with just a simple click it would be merged

**Comment by km-ch** [comment]
one lil thing, you forgot to include the option to toggle resolverpitch

**Comment by SomeExtraChips** [comment]
yea ima do that

**Comment by km-ch** [comment]
Wait, I just made the code

**Comment by km-ch** [comment]
I have everything done, the menu and configs stuff, but I forgot to pr it and I'm out of my home until tomorrow. Once I'm back, I'll pr it

Warning, it is dogshit and it only hits if you are using up or down (no half, half up, etc), and if you aren't using yaw anti aim

**Comment by SomeExtraChips** [comment]
well for yaw i think you can use m_angEyeAngles[1] with a keybind system to toggle right/left
