### ISSUE TITLE
Crit hack

### ISSUE THREAD

**Issue by PSSGAMER** [M-FeD/Fedoraware#29]
The crithack source at unknowncheats is available. Try adding that. Also this is the wrong pace to post suggestions then tell me a just made a GitHub account to suggest you this.

**Comment by oxyGodmode** [comment]
We know that the crithack sources are on UC , it is also in cathook , but still, as soon as possible, we will make it, we have already answered this question more than once.

**Comment by M-FeD** [comment]
> 
> 
> The crithack source at unknowncheats is available. Try adding that. Also this is the wrong pace to post suggestions then tell me a just made a GitHub account to suggest you this.

I don't know how to implement it.

**Comment by km-ch** [comment]
paste * :trololo:On Sep 13, 2021 11:25, M-FeD ***@***.***> wrote:

The crithack source at unknowncheats is available. Try adding that. Also this is the wrong pace to post suggestions then tell me a just made a GitHub account to suggest you this.

I don't know how to implement it.

**Comment by M-FeD** [comment]
> 
> paste * :trololo:On Sep 13, 2021 11:25, M-FeD ***@***.***> wrote: The crithack source at unknowncheats is available. Try adding that. Also this is the wrong pace to post suggestions then tell me a just made a GitHub account to suggest you this. I don't know how to implement it. —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

what

**Comment by justkamiii** [comment]
Wtf, GitHub mail reply broke
