### ISSUE TITLE
My ImGui theme

### ISSUE THREAD

**Issue by oxyGodmode** [M-FeD/Fedoraware#33]
I decided to try to make my own theme
too, maybe someone will not like it, but I think it turned out pretty well.

So, here we go:

    ImGuiStyle* style = dst ? dst : &ImGui::GetStyle();
    ImVec4* colors = style->Colors;

    colors[ImGuiCol_Text] = ImVec4(0.90f, 1.00f, 1.00f, 1.00f);
    colors[ImGuiCol_TextDisabled] = ImVec4(0.60f, 0.60f, 1.00f, 1.00f);
    colors[ImGuiCol_WindowBg] = ImVec4(0.00f, 0.00f, 0.00f, 0.80f);
    colors[ImGuiCol_PopupBg] = ImVec4(0.05f, 0.05f, 0.14f, 0.90f);
    colors[ImGuiCol_Border] = ImVec4(0.70f, 1.00f, 0.82f, 1.00f);
    colors[ImGuiCol_BorderShadow] = ImVec4(0.00f, 0.00f, 0.00f, 0.00f);
    colors[ImGuiCol_FrameBg] = ImVec4(1.00f, 0.91f, 1.00f, 0.06f);
    colors[ImGuiCol_FrameBgHovered] = ImVec4(0.43f, 0.91f, 0.85f, 0.35f);
    colors[ImGuiCol_FrameBgActive] = ImVec4(0.00f, 0.00f, 0.66f, 0.21f);
    colors[ImGuiCol_TitleBg] = ImVec4(0.00f, 0.59f, 0.40f, 0.07f);
    colors[ImGuiCol_TitleBgCollapsed] = ImVec4(0.40f, 0.40f, 0.65f, 0.20f);
    colors[ImGuiCol_TitleBgActive] = ImVec4(0.00f, 0.00f, 0.00f, 1.00f);
    colors[ImGuiCol_MenuBarBg] = ImVec4(0.40f, 0.40f, 0.55f, 0.16f);
    colors[ImGuiCol_ScrollbarBg] = ImVec4(0.00f, 0.01f, 0.27f, 0.35f);
    colors[ImGuiCol_ScrollbarGrab] = ImVec4(0.00f, 0.00f, 0.05f, 0.13f);
    colors[ImGuiCol_ScrollbarGrabHovered] = ImVec4(0.40f, 0.40f, 0.80f, 0.40f);
    colors[ImGuiCol_ScrollbarGrabActive] = ImVec4(0.80f, 0.50f, 0.50f, 0.40f);
    colors[ImGuiCol_CheckMark] = ImVec4(0.90f, 0.90f, 0.90f, 0.50f);
    colors[ImGuiCol_SliderGrab] = ImVec4(0.00f, 0.75f, 1.00f, 0.14f);
    colors[ImGuiCol_SliderGrabActive] = ImVec4(0.81f, 0.95f, 1.00f, 0.15f);
    colors[ImGuiCol_Button] = ImVec4(0.00f, 0.25f, 0.29f, 0.65f);
    colors[ImGuiCol_ButtonHovered] = ImVec4(0.00f, 0.00f, 0.00f, 0.51f);
    colors[ImGuiCol_ButtonActive] = ImVec4(1.f, 1.f, 1.f, 0.56f);
    colors[ImGuiCol_Header] = ImVec4(0.00f, 0.25f, 0.29f, 0.65f);
    colors[ImGuiCol_HeaderHovered] = ImVec4(0.45f, 0.45f, 0.90f, 0.00f);
    colors[ImGuiCol_HeaderActive] = ImVec4(0.53f, 0.53f, 0.87f, 0.25f);
    colors[ImGuiCol_ResizeGrip] = ImVec4(1.00f, 1.00f, 1.00f, 0.30f);
    colors[ImGuiCol_ResizeGripHovered] = ImVec4(1.00f, 1.00f, 1.00f, 0.60f);
    colors[ImGuiCol_ResizeGripActive] = ImVec4(1.00f, 1.00f, 1.00f, 0.90f);
    colors[ImGuiCol_PlotLines] = ImVec4(1.00f, 1.00f, 1.00f, 1.00f);
    colors[ImGuiCol_PlotLinesHovered] = ImVec4(0.90f, 0.70f, 0.00f, 1.00f);
    colors[ImGuiCol_PlotHistogram] = ImVec4(0.90f, 0.70f, 0.00f, 1.00f);
    colors[ImGuiCol_PlotHistogramHovered] = ImVec4(1.00f, 0.60f, 0.00f, 1.00f);
    colors[ImGuiCol_TextSelectedBg] = ImVec4(0.00f, 0.00f, 1.00f, 0.35f);
    
    
![Team Fortress 2 Screenshot 2021 09 15 - 04 48 13 24](https://user-images.githubusercontent.com/87392051/133357233-5784b07a-2051-4ce0-9792-81c286ae75e9.png)

**Comment by JAGNEmk** [comment]
Looks really nice, i'd just replace the cyan with something brighter ig

**Comment by M-FeD** [comment]
Maybe we should put all these in one thread?

**Comment by oxyGodmode** [comment]
> Maybe we should put all these in one thread?

We can just close the previous 2 topics, and name one topic "Your ImGui developments"
Or something like that.
