### ISSUE TITLE
Keeps saying "unable to start program" and "system can't find the specific file"

### ISSUE THREAD

**Issue by Iwannapoop** [M-FeD/Fedoraware#40]
I downloaded the download zip, extracted the file, and opened SE-Owned.sln, and tried to compile it into a Dll using visual studios 2019 community edition I tried to batch build it and used the solution configure I checked the tutorial, reinstalled my visual studios and checked how to fix this but nothing. can you help me?

![image](https://user-images.githubusercontent.com/90901609/133762083-c5e8950e-484b-4dd8-b19d-de2a63ec268d.png)

**Comment by km-ch** [comment]
Yeah, it was an oopsie I made. I forgot to add a ; and some other shit lol. Try recompiling

**Comment by km-ch** [comment]
Actually, wait for the last pull request to be merged
