### ISSUE TITLE
Viewmodels disappear on different angles

### ISSUE THREAD

**Issue by Iwannapoop** [M-FeD/Fedoraware#43]
Viewmodels disappear when I try to look at different angles I confirmed that it's not the mod I'm using because it happens to every single weapon

**Comment by M-FeD** [comment]
why

**Comment by justkamiii** [comment]
@Iwannapoop Can you please record a video showing the issue?

**Comment by lykanfox** [comment]
a6c153a

**Comment by frel0** [comment]
> Viewmodels disappear when I try to look at different angles I confirmed that it's not the mod I'm using because it happens to every single weapon

Recompile

**Comment by Iwannapoop** [comment]
nvm it works viewmodels don't disappear
