### ISSUE TITLE
increase fakelag ticks

### ISSUE THREAD

**Issue by rikodeine** [M-FeD/Fedoraware#5]
why you got it capped at 14 ticks bra
increase to 24

**Comment by rikodeine** [comment]
also add fakelag chams smh

**Comment by M-FeD** [comment]
> 
> 
> also add fakelag chams smh

how?



> 
> 
> why you got it capped at 14 ticks bra
> increase to 24

increase it to 24, test it and submit a PR if it works

**Comment by IamIndeedGamingAsHardAsICan03489** [comment]
why you got it capped at 14 ticks bra, set it to 21, if u know how to bypass cl_sendmove fakelag limit, hf with 23

**Comment by M-FeD** [comment]
https://github.com/M-FeD/Fedoraware/commit/3b9f2411aa4274fcf2d961de99c54b4276e2c641

If you wanted it above 14 you could have edited the config, however I have now changed the slider to be capped at 21.
