### ISSUE TITLE
how do u do font changing in the new menu

### ISSUE THREAD

**Issue by rikodeine** [M-FeD/Fedoraware#6]
fucking good job on the imgui menu boys mad impressed
how do you change fonts on it but

**Comment by M-FeD** [comment]
`Normal = io.Fonts->AddFontFromFileTTF(u8"C:\\Windows\\Fonts\\tahomabd.ttf", 14.0f, &m_font_config, io.Fonts->GetGlyphRangesCyrillic());`
replace tahomabd.ttf with a truetype font of your choosing
