### ISSUE TITLE
how do i fix the brightness after i injected it

### ISSUE THREAD

**Issue by dicksonmyface** [M-FeD/Fedoraware#60]
![Screenshot (134)](https://user-images.githubusercontent.com/91516638/135024467-29d914e5-27bc-4b6d-83ad-94cfd03e46b2.png)

**Comment by l-r00t-l** [comment]
World modulation? But it won't change the menu brightness

**Comment by M-FeD** [comment]
what the hell

**Comment by dicksonmyface** [comment]
> World modulation? But it won't change the menu brightness

it still doesnt work

**Comment by SinnerTF2** [comment]
what are your launch options?

**Comment by dicksonmyface** [comment]
> what are your launch options?

-dxlevel 81 -windowed -w 854 -h 480 -novid

**Comment by M-FeD** [comment]
i think anything under dx9 will be fucky, switch to dxlevel 90+

**Comment by SinnerTF2** [comment]
yeah just tested it with dxlevel 81 and it broke
![image](https://user-images.githubusercontent.com/64489962/135070847-cf977e5d-0adc-4fbb-a9a1-7fbca25d5886.png)

**Comment by M-FeD** [comment]
just pushed a "fix" of sorts for this, lmk if it helps
https://github.com/M-FeD/Fedoraware/commit/36fe4139a9fd8a5bdd4eb8197d5ecbfffb8c2154
