### ISSUE TITLE
Huntsman

### ISSUE THREAD

**Issue by ipecarvalho** [M-FeD/Fedoraware#62]
Projectile aimbot dont work with huntsman (bow for sniper)

**Comment by IIllIIllIIIIl** [comment]
just turn off "aimbot smooth if spectated"

**Comment by l-r00t-l** [comment]
Que?

https://youtu.be/7gDLPRXtdw8

**Comment by ipecarvalho** [comment]
> Que?
> 
> https://youtu.be/7gDLPRXtdw8
> 
> Show us your aimbot tab



> just turn off "aimbot smooth if spectated"

I did it,sometimes it shoots at the ground and other times it miss on a enemy that is going on a straight line

**Comment by ipecarvalho** [comment]
> Que?
> 
> https://youtu.be/7gDLPRXtdw8
> 
> Show us your aimbot tab

**Comment by ipecarvalho** [comment]
> Que?
> 
> https://youtu.be/7gDLPRXtdw8
> 
> Show us your aimbot tab

Give me a minute

**Comment by ipecarvalho** [comment]
> Que?
> 
> https://youtu.be/7gDLPRXtdw8
> 
> Show us your aimbot tab

![image](https://user-images.githubusercontent.com/91567916/135182278-a0ab2ad2-fad6-4994-a8a1-aea3f8064d53.png)

**Comment by JAGNEmk** [comment]
I don't see why it wouldn't work

**Comment by ipecarvalho** [comment]
> I don't see why it wouldn't work

it KINDA works,it just headshot 1 time per hour

**Comment by IIllIIllIIIIl** [comment]
bruh you have 5 fov aimbot thats why

**Comment by M-FeD** [comment]
he has 24 on projectile

**Comment by canedoly** [comment]
huntsman is an projectile not hitscan

**Comment by HutchyBean** [comment]
maybe they think they can hit scouts that change direction every nano second (you cant (usually))

**Comment by IIllIIllIIIIl** [comment]
maybe change auto to head idk

**Comment by HutchyBean** [comment]
auto targets head on huntsman

**Comment by ipecarvalho** [comment]
> bruh you have 5 fov aimbot thats why

Huntsman is a projectile,dumb

**Comment by ipecarvalho** [comment]
> maybe change auto to head idk

There is no option to it,there is only body,feet and auto

**Comment by ipecarvalho** [comment]
> auto targets head on huntsman

Look at my last comment

**Comment by HutchyBean** [comment]
> > auto targets head on huntsman
> 
> Look at my last comment

Look at my last comment (I SAID IT TARGETS HEAD WHEN AUTO)

**Comment by ipecarvalho** [comment]
> > > auto targets head on huntsman
> > 
> > 
> > Look at my last comment
> 
> Look at my last comment (I SAID IT TARGETS HEAD WHEN AUTO)

Holy shit my guy,i just read wrong,calm down

**Comment by HutchyBean** [comment]
YOU STINKY HEad

**Comment by ipecarvalho** [comment]
> YOU STINKY HEad

Oke

**Comment by M-FeD** [comment]
what the hell

**Comment by Byotic** [comment]
loooool huntsman proj aim bad lmaoooo

**Comment by ipecarvalho** [comment]
> maybe they think they can hit scouts that change direction every nano second (you cant (usually))

No,i sometimes i cant even headshot a standing still heavy

**Comment by JAGNEmk** [comment]
Wdym, does it shoot too high or does it bodyshot?

**Comment by ipecarvalho** [comment]
> Wdym, does it shoot too high or does it bodyshot?

bodyshot and some times it just shoot on the feet

**Comment by km-ch** [comment]
Could you please provide video evidence of this? You can use a program like OBS to do so

**Comment by oxyGodmode** [comment]
https://youtu.be/tUO4XkOWM9k

The aimbot works fine, if you want to configure it the way I have, just click on pause, and so, it's closed.
If something is still wrong, then update your version of the cheat

**Comment by JAGNEmk** [comment]
https://github.com/M-FeD/Fedoraware/pull/86

try messing around with the z adjust, between 5-7 seems p
if it overshoots just lower it

**Comment by JAGNEmk** [comment]
nooo my sald
