### ISSUE TITLE
[Feature Request] Add a auto-charge DT option

### ISSUE THREAD

**Issue by raspimana** [M-FeD/Fedoraware#65]
Title says it all. Add a option to auto-charge double-tap. Pressing H gets tiring, you know.

While you're here, here's a dog I found. 
![image](https://user-images.githubusercontent.com/36178983/135368681-7c5bd76d-4678-4f50-8f1a-f1cae4c77714.png)

**Comment by ipecarvalho** [comment]
the most close to this is the always doubletap thing

**Comment by raspimana** [comment]
> the most close to this is the always doubletap thing

Yep. Sadly, it doesn't auto-charge in it. Could add it there.

**Comment by M-FeD** [comment]
cool dog

**Comment by HutchyBean** [comment]
I'll do this after back from college. If no-one else does

**Comment by JAGNEmk** [comment]
@HutchyBean im have it done already, will push after i get back from school

**Comment by HutchyBean** [comment]
How does it work? I was gunna do something like lbox(?) and charge when standing still

**Comment by M-FeD** [comment]
> 
> 
> How does it work? I was gunna do something like lbox(?) and charge when standing still

wow this is what i was gonna do

**Comment by JAGNEmk** [comment]
It just recharges when its empty

**Comment by HutchyBean** [comment]
That is not good idea cause it would end up recharging at dumb time !

**Comment by M-FeD** [comment]
I added it properly (non stupid way)

**Comment by HutchyBean** [comment]
God liek

**Comment by M-FeD** [comment]
https://github.com/M-FeD/Fedoraware/commit/d31623903f62669afbc1a37965545a1907cdb0b3 boom bang pow try it out

**Comment by JAGNEmk** [comment]
Yes

**Comment by JAGNEmk** [comment]
Added, closing this now
