### ISSUE TITLE
Consistent Crash

### ISSUE THREAD

**Issue by km-ch** [M-FeD/Fedoraware#76]
---
name: Bug Report
about: Create a report and help us improve Fedoraware!
title: A quick Description of Bug
labels: bug
assignees: ''
---

**Fedoraware Version Date:**  

## Config used:

https://files.catbox.moe/gqoo79.seo

## Description:  

TF2 will crash if you open the menu before Wheatley finishes saying "Okay, I'm about to start hacking"

## Steps to reproduce:  
- [x] I am able to consistently reproduce this error

1- Load TF2
2- Inject Fedoraware
3- As soon as you hear Wheatley say "Okay, I'm about to start hacking", open the menu
4- The game will freeze, with the audio stuttering forever

## Additional context 

N/A

## Screenshot of cheats enabled  

N/A

- [x] I have included the steps to reproduce and my logs to the best I am able to share.

**Comment by km-ch** [comment]
This wasn't as consistent as I though, but I did get @HutchyBean to crash. We are testing in voice-chat

**Comment by HutchyBean** [comment]
ben is godlike and potentially found source of issue being the old menu

**Comment by cheekybaguette** [comment]
ben is retarded and stupid and a faggot and a nigger

**Comment by M-FeD** [comment]
you

**Comment by cheekybaguette** [comment]
mfed stinks like poopies L0L

**Comment by AscendedSion** [comment]
m-fed is a poopy poo poo

**Comment by AscendedSion** [comment]
+ pc issue, get a better pc then try injecting fedoraware........................ smh.............
