### ISSUE TITLE
Add followbot

### ISSUE THREAD

**Issue by raspimana** [M-FeD/Fedoraware#80]
Think it would be cool, especially with sandboxie for a medic bot. :)
(also, could add a walkbot, but might be too hard?)

As tradition for me, here's a cute dog I found.
![image](https://user-images.githubusercontent.com/36178983/136640457-3a8f1f28-e38c-4ee3-93a8-10c9a5a032ee.png)

**Comment by JAGNEmk** [comment]
Maybe, noted.
