### ISSUE TITLE
selfillum material ugly :(

### ISSUE THREAD

**Issue by spook953** [M-FeD/Fedoraware#9]
Proper:
![Alt Text](https://i.imgur.com/MyLfzQS.png)
regarding $phongfresnelranges, they should be: mat_hdr_level->GetInt() > 1 ? "[0 0.05 0.1]" : "[0 1.5 2]"
oh and this requires like.. mat_phong 1, mat_specular 1, mat_bumpmap 1 and maybe something else too

**Comment by M-FeD** [comment]
https://github.com/M-FeD/Fedoraware/commit/881f6354e8a3d19fe6d213aa5d7a2b3750872621
How about this? Will be rainbow on local player if rainbow glow is enabled, you can change the base(?) colour, and it accounts for the HDR setting. thanks!

**Comment by M-FeD** [comment]
Considering this closed
