### ISSUE TITLE
discord link no worky =(

### ISSUE THREAD

**Issue by raspimana** [M-FeD/Fedoraware#99]
![image](https://user-images.githubusercontent.com/36178983/137598420-4c109f16-9413-4247-b353-f59c8673d3c4.png)

sadge

EDIT: Almost forgot about my dog. Great cheat, keep it up!
![image](https://user-images.githubusercontent.com/36178983/137599220-9ae8d171-d83d-4236-8f5a-ed22430e356d.png)

**Comment by JAGNEmk** [comment]
https://discord.gg/V43V9dgJQp

**Comment by raspimana** [comment]
thanks
